# Generated by Django 5.0.6 on 2024-06-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_contacto', models.AutoField(db_column='idContacto', primary_key=True, serialize=False)),
                ('nombrepri', models.CharField(max_length=50)),
                ('apellidopa', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_produ', models.AutoField(db_column='idProdu', primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('foto', models.ImageField(null=True, upload_to='media')),
            ],
        ),
    ]
