# Generated by Django 5.0.6 on 2024-06-27 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_remove_contacto_id_contacto_contacto_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id_tipo', models.AutoField(db_column='idTipo', primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='productos',
            name='id_tipo',
            field=models.ForeignKey(db_column='idTipo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.tipoproducto'),
        ),
    ]
